name: Docker
on: [workflow_dispatch]

jobs:
    docker-job:
        runs-on: ubuntu-latest
        container:
            image: node:20.3-alpine3.17
            env:
                API_URL: some-url.com
            ports:
                - 80
        steps:
            - name: Log Node & os version
              run: |
                node -v
                cat /etc/os-release
            - name: Log Env
              run: echo $API_URL
