name: Repository Events
on: [push, pull_request, issues]

jobs:
    checkout-test:
        runs-on: ubunut-latest
        steps:
            - run: |
                echo $GITHUB_SHA
                echo $GITHUB_REF
            - uses: actions/checkout@v4
