name: Expressions and Contexts
on: [push, pull_request, issues, workflow_dispatch]
run-name: "Expressions & Contexts by @${{ github.actor }}, event: ${{ github.event_name }}"

jobs:
    runs-on-issues-and-prs:
        runs-on: ubuntu-latest
        if: contains(fromJson('["issues", "pull_request"]'), github.event_name)
        steps:
            - name: Run only if issue has a bug label
              #.* returns array of named properties of object
              if: contains(github.event.issue.labels.*.name, 'bug')
              run: echo ${{ join(github.event.issue.labels.*.name, ', ') }}

    using-expressions-and-contexts:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
            - name: Expressiones
              id: expressiones
              run: |
                echo ${{ 1 }}
                echo ${{ 'This is a string' }}
                echo ${{ null }}
                echo ${{ true }}
                echo ${{ 1 > 2 }}
                echo ${{ 'string' == 'String' && false }}
            - name: Dump Contexts
              run: |
                echo '${{ toJson(github) }}'
                echo '${{ toJson(job) }}'
                echo '${{ toJson(secrets) }}'
                echo '${{ toJson(runner) }}'
                echo '${{ toJson(steps) }}'