name: Matrix
on: [push]

jobs:
    node-matrix:
        strategy:
            # Will run number of possible combinations
            matrix:
                os: [windows-latest, ubuntu-latest]
                node-version: [14, 15, 16]
        runs-on: ${{ matrix.os }}
        steps:
            - run: node -v
            - uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            - run: node -v